---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 51.250.71.160
    jenkins-agent-01:
      ansible_host: 130.193.38.176
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: roman